// <auto-generated />
using System;
using CovadisLeenAuto.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovadisLeenAuto.Domain.Migrations
{
    [DbContext(typeof(LeenAutoContext))]
    [Migration("20250612133554_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CovadisLeenAuto.Domain.Enitities.LeenAuto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Gereserveerd")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GereserveerdTot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GereserveerdVan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("LeenAutos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Gereserveerd = false,
                            GereserveerdTot = new DateTime(2025, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GereserveerdVan = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kenteken = "aa11bc2",
                            KilometerStand = 1234,
                            Type = "Honda Civic"
                        },
                        new
                        {
                            ID = 2,
                            Gereserveerd = false,
                            GereserveerdTot = new DateTime(2022, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GereserveerdVan = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kenteken = "mw-99-99",
                            KilometerStand = 1010,
                            Type = "Fiat Multipla"
                        },
                        new
                        {
                            ID = 3,
                            Gereserveerd = true,
                            GereserveerdTot = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GereserveerdVan = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Kenteken = "qa-12-30",
                            KilometerStand = 500,
                            Type = "BMW M5"
                        });
                });

            modelBuilder.Entity("CovadisLeenAuto.Domain.Enitities.Rit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeginDatum")
                        .HasColumnType("TEXT");

                    b.Property<string>("EindAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EindDatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometerStandBegin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilometerStandEind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeenautoID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartAdres")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WerknemerID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("LeenautoID");

                    b.HasIndex("WerknemerID");

                    b.ToTable("Ritten");
                });

            modelBuilder.Entity("CovadisLeenAuto.Domain.Enitities.Werknemer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Werknemers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Naam = "Mathijs"
                        },
                        new
                        {
                            ID = 2,
                            Naam = "Emilio"
                        },
                        new
                        {
                            ID = 3,
                            Naam = "Juan"
                        });
                });

            modelBuilder.Entity("CovadisLeenAuto.Domain.Enitities.Rit", b =>
                {
                    b.HasOne("CovadisLeenAuto.Domain.Enitities.LeenAuto", "Leenauto")
                        .WithMany()
                        .HasForeignKey("LeenautoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CovadisLeenAuto.Domain.Enitities.Werknemer", "Werknemer")
                        .WithMany()
                        .HasForeignKey("WerknemerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leenauto");

                    b.Navigation("Werknemer");
                });
#pragma warning restore 612, 618
        }
    }
}
